"""
Type stubs for ufbx.core module
"""

from collections.abc import Iterator
from types import TracebackType
from typing import Any, List, Optional

class Vec2:
    """2D Vector"""
    x: float
    y: float

    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...
    @classmethod
    def from_c(cls, c_vec: Any) -> Vec2: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[float]: ...


class Vec3:
    """3D Vector"""
    x: float
    y: float
    z: float

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    @classmethod
    def from_c(cls, c_vec: Any) -> Vec3: ...
    def to_c(self) -> Any: ...
    def normalize(self) -> Vec3: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[float]: ...


class Vec4:
    """4D Vector"""
    x: float
    y: float
    z: float
    w: float

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, w: float = 0.0) -> None: ...
    @classmethod
    def from_c(cls, c_vec: Any) -> Vec4: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[float]: ...


class Quat:
    """Quaternion"""
    x: float
    y: float
    z: float
    w: float

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, w: float = 1.0) -> None: ...
    @classmethod
    def from_c(cls, c_quat: Any) -> Quat: ...
    def to_c(self) -> Any: ...
    def normalize(self) -> Quat: ...
    def __mul__(self, other: Quat) -> Quat: ...
    def __repr__(self) -> str: ...


class Matrix:
    """4x4 Matrix"""
    m: List[List[float]]

    def __init__(self, m: Optional[List[List[float]]] = None) -> None: ...
    @classmethod
    def from_c(cls, c_matrix: Any) -> Matrix: ...
    def __repr__(self) -> str: ...


class Transform:
    """Transform (translation, rotation, scale)"""
    translation: Vec3
    rotation: Quat
    scale: Vec3

    def __init__(
        self,
        translation: Optional[Vec3] = None,
        rotation: Optional[Quat] = None,
        scale: Optional[Vec3] = None
    ) -> None: ...
    @classmethod
    def from_c(cls, c_transform: Any) -> Transform: ...
    def to_matrix(self) -> Matrix: ...
    def __repr__(self) -> str: ...


class Element:
    """Base class for all scene elements"""
    _ptr: Any

    def __init__(self, c_ptr: Any) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def element_id(self) -> int: ...
    @property
    def typed_id(self) -> int: ...
    @property
    def type(self) -> int: ...
    def __repr__(self) -> str: ...


class Node(Element):
    """Scene node with transform and hierarchy"""
    @property
    def parent(self) -> Optional[Node]: ...
    @property
    def children(self) -> List[Node]: ...
    @property
    def local_transform(self) -> Transform: ...
    @property
    def node_to_world(self) -> Matrix: ...
    @property
    def node_to_parent(self) -> Matrix: ...
    @property
    def mesh(self) -> Optional[Mesh]: ...
    @property
    def light(self) -> Optional[Light]: ...
    @property
    def camera(self) -> Optional[Camera]: ...
    @property
    def bone(self) -> Optional[Bone]: ...
    @property
    def visible(self) -> bool: ...
    @property
    def is_root(self) -> bool: ...
    @property
    def materials(self) -> List[Material]: ...


class Mesh(Element):
    """Polygonal mesh geometry"""
    @property
    def num_vertices(self) -> int: ...
    @property
    def num_indices(self) -> int: ...
    @property
    def num_faces(self) -> int: ...
    @property
    def num_triangles(self) -> int: ...
    @property
    def vertex_position(self) -> List[Vec3]: ...
    @property
    def vertex_normal(self) -> List[Vec3]: ...
    @property
    def vertex_uv(self) -> List[Vec2]: ...
    @property
    def materials(self) -> List[Material]: ...
    @property
    def skin_deformers(self) -> List[SkinDeformer]: ...
    @property
    def blend_deformers(self) -> List[BlendDeformer]: ...
    def triangulate_face(self, face_index: int) -> List[int]: ...


class Light(Element):
    """Light source"""
    @property
    def color(self) -> Vec3: ...
    @property
    def intensity(self) -> float: ...
    @property
    def light_type(self) -> int: ...


class Camera(Element):
    """Camera"""
    @property
    def projection_mode(self) -> int: ...
    @property
    def resolution(self) -> Vec2: ...
    @property
    def field_of_view_deg(self) -> Vec2: ...
    @property
    def near_plane(self) -> float: ...
    @property
    def far_plane(self) -> float: ...


class Bone(Element):
    """Bone information"""
    @property
    def radius(self) -> float: ...
    @property
    def relative_length(self) -> float: ...


class Material(Element):
    """Surface material"""
    @property
    def shader_type(self) -> int: ...
    @property
    def textures(self) -> List[Texture]: ...


class Texture(Element):
    """Texture"""
    @property
    def texture_type(self) -> int: ...
    @property
    def filename(self) -> str: ...
    @property
    def absolute_filename(self) -> str: ...
    @property
    def relative_filename(self) -> str: ...


class Anim:
    """Animation descriptor"""
    _ptr: Any

    def __init__(self, c_ptr: Any) -> None: ...
    @property
    def time_begin(self) -> float: ...
    @property
    def time_end(self) -> float: ...


class AnimStack(Element):
    """Animation stack"""
    @property
    def time_begin(self) -> float: ...
    @property
    def time_end(self) -> float: ...
    @property
    def anim(self) -> Anim: ...


class AnimLayer(Element):
    """Animation layer"""
    @property
    def weight(self) -> float: ...


class AnimCurve(Element):
    """Animation curve"""
    @property
    def min_value(self) -> float: ...
    @property
    def max_value(self) -> float: ...
    def evaluate(self, time: float, default_value: float = 0.0) -> float: ...


class SkinDeformer(Element):
    """Skeletal skinning deformer"""
    @property
    def skinning_method(self) -> int: ...
    @property
    def clusters(self) -> List[SkinCluster]: ...


class SkinCluster(Element):
    """Single bone cluster in skin deformer"""
    @property
    def bone_node(self) -> Node: ...
    @property
    def geometry_to_bone(self) -> Matrix: ...


class BlendDeformer(Element):
    """Blend shape deformer"""
    @property
    def channels(self) -> List[BlendChannel]: ...


class BlendChannel(Element):
    """Blend shape channel"""
    @property
    def weight(self) -> float: ...


class BlendShape(Element):
    """Blend shape target"""
    ...


class CacheDeformer(Element):
    """Geometry cache deformer"""
    ...


class CacheFile(Element):
    """Cache file reference"""
    ...


class Constraint(Element):
    """Constraint"""
    @property
    def constraint_type(self) -> int: ...


class DisplayLayer(Element):
    """Display layer"""
    ...


class SelectionSet(Element):
    """Selection set"""
    ...


class Character(Element):
    """Character definition"""
    ...


class Scene:
    """FBX Scene Wrapper Class"""
    _scene: Any
    _closed: bool

    def __init__(self, scene_ptr: Any) -> None: ...
    @classmethod
    def load_file(cls, filename: str, opts: Any = None) -> Scene: ...
    @classmethod
    def load_memory(cls, data: bytes, opts: Any = None) -> Scene: ...
    def close(self) -> None: ...
    def __del__(self) -> None: ...
    def __enter__(self) -> Scene: ...
    def __exit__(
        self,
        exc_type: Optional[type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType]
    ) -> bool: ...
    @property
    def metadata(self) -> Any: ...
    @property
    def root_node(self) -> Node: ...
    @property
    def nodes(self) -> List[Node]: ...
    @property
    def meshes(self) -> List[Mesh]: ...
    @property
    def lights(self) -> List[Light]: ...
    @property
    def cameras(self) -> List[Camera]: ...
    @property
    def materials(self) -> List[Material]: ...
    @property
    def textures(self) -> List[Texture]: ...
    @property
    def anim_stacks(self) -> List[AnimStack]: ...
    @property
    def node_count(self) -> int: ...
    @property
    def mesh_count(self) -> int: ...
    @property
    def light_count(self) -> int: ...
    @property
    def camera_count(self) -> int: ...
    @property
    def material_count(self) -> int: ...
    @property
    def texture_count(self) -> int: ...
    @property
    def animation_count(self) -> int: ...
    def find_node(self, name: str) -> Optional[Node]: ...
    def find_material(self, name: str) -> Optional[Material]: ...
    def find_anim_stack(self, name: str) -> Optional[AnimStack]: ...
    def evaluate_scene(self, anim: Optional[Anim], time: float) -> Scene: ...
    def __repr__(self) -> str: ...


def load_file(filename: str) -> Scene: ...
def load_memory(data: bytes) -> Scene: ...
